### ISSUE TITLE
Remove dependency on go.opentelemetry.io/collector/config/configtls.TLSServerSetting

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-log-collection#119]
> Given that we plan to move `filelog` to the core we are going to have a circular dependency. We need to think about how to break this.

_Originally posted by @tigrannajaryan in https://github.com/open-telemetry/opentelemetry-log-collection/issues/101#issuecomment-823610063_

Need to determine:
- Will this cause a circular dependency when `filelog` is moved into core?
- If so, what refactoring / changes are necessary to avoid this?

**Comment by djaglowski** [comment]
I've determined that only `go.opentelemetry.io/collector/config/configtls.TLSServerSetting` is being used, and only in `tcp_input` and `syslog_input`.

My understanding of golang dependency management is not perfect. In particular, I'm a little unsure if module-level cycles are a concern or not. I haven't been able to find a clear explanation of this. So with that in mind, please double check my thinking here:

We shouldn't have any problem if the only requirement is avoiding a circular dependency between packages, since `configtls` is not ever going to depend on any package in this repo.

However, if we need to avoid a circular dependency between modules, then we may have an issue. If needed, we can probably hide `configtls.TLSServerSetting` behind an interface somehow - I haven't worked through this exactly yet.

In any case, I make a throwaway PR to test out whether we may have an issue, and [it can at least compile](https://github.com/open-telemetry/opentelemetry-collector/pull/2981/checks?check_run_id=2403972182), which I believe validates that we won't have an issue here.

**Comment by tigrannajaryan** [comment]
Even if it is allowed to have a circular dependency between go modules it still look untidy to me. It would be great if we can break it. I am not sure why we import TLSServerSetting here, I haven't read the code. Perhaps we do what you suggested, convert to interface here which TLSServerSetting satisfies.

**Comment by djaglowski** [comment]
Any solution should ensure that `TLSServerSetting` is still part of configuration for [syslogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/syslogreceiver#tls-configuration) and any other log receivers making use of the struct at the time of the change.

**Comment by tigrannajaryan** [comment]
Yes, but we don't need the actual `TLSServerSetting` struct in this repo, do we?
This repo can declare: 
```go
type TLSServerSetting interface {
  LoadTLSConfig() (*tls.Config, error)
}
```
From what I see we only [call LoadTLSConfig()](https://github.com/open-telemetry/opentelemetry-log-collection/blob/d73dd053888f2bad4b01f7930084999caaf6ced0/operator/builtin/input/tcp/tcp.go#L99) and [decode YAML](https://github.com/open-telemetry/opentelemetry-log-collection/blob/d73dd053888f2bad4b01f7930084999caaf6ced0/operator/helper/tls.go#L38) into the struct in this repo. I think an interface should work (not completely sure about decoding YAML).

I did not look into full details of what else this would require. Somehow we would need to pass an instance of `go.opentelemetry.io/collector/config/configtls.TLSServerSetting` struct when this repo needs to deal with `TLSServerSetting` interface that it declares.

I _think_ it should be possible, but not completely sure without reading more of the code.

**Comment by djaglowski** [comment]
@tigrannajaryan, I agree with you - was just documenting the minimal requirement for the work.

**Comment by rockb1017** [comment]
Hi @djaglowski 
what is latest status on this one?
