### ISSUE TITLE
tcp_input - Support additional configuration from file_input

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-log-collection#120]
Should investigate and if possible support `multiline`, `max_log_size` and `encoding`.

_Originally posted by @tigrannajaryan in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3190#r618678509_

**Comment by sumo-drosiek** [comment]
Proposal for `multiline` and `encoding`:
https://github.com/open-telemetry/opentelemetry-log-collection/pull/125

**Comment by djaglowski** [comment]
Closed via #125. Thanks @sumo-drosiek!
