### ISSUE TITLE
Create syslog input operator

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-log-collection#13]
- Should be a composition of `tcp_input`, `udp_input` and `syslog_parser` 
- Should not result in the removal of the above operators (just compose them and make them available as one)
- Should allow user to specify either tcp or udp

**Comment by WPH95** [comment]
I'm filebeat Syslog input contribute. If no one is currently working on this issue, I can do it :)

- Do you mind using ragel to parse syslog
- which syslog format support, RFC3164? RFC5424? or both
