### ISSUE TITLE
Add a badge for CI status and CodeCov

### ISSUE THREAD

**Issue by KKelvinLo** [open-telemetry/opentelemetry-log-collection#152]
**Is your feature request related to a problem?**
Most of the existing OpenTelemetry repositories display a badge for CI status and code coverage. In an effort to have the log-collection repository to be up to date and consistent with the other established SDKs and repositories, there should be a status tracking badge in the main README.md file.

**Describe the solution you'd like.**
As a developer contributing to OpenTelemetry, I recommend adding a CI status and code coverage percentage badge at the top of the README document of the log-collection repo. Code coverage and CI badges are a common feature of many modern open source projects, which improves readability and convenience to developers. By adding CI and codecoverage badges to the README.md, with a quick scan, any observer will be able to know the status of the repository. 

cc: @alolita

**Comment by djaglowski** [comment]
@KKelvinLo, this is a very welcome suggestion. We stripped out a few standard integration items like these, when we transferred the repo into the OTel org. Thanks for calling these out.

If you have time to make a PR, that would be most welcome. Otherwise, I'll try to grab this one next week.
