### ISSUE TITLE
Plugins for custom backends

### ISSUE THREAD

**Issue by ttomsu** [open-telemetry/opentelemetry-log-collection#177]
Hi! This project looks really neat! 

I noticed some differences between the OT version and the [older observIQ version](https://github.com/observIQ/stanza) - notably some of the more advanced outputs are missing. When I read that it supports "plugins", I thought it would be possible to write my own for our custom backend - but it looks like I would have to fork the project build it myself. 

Are true custom backend plugins on the roadmap?

**Comment by djaglowski** [comment]
Hi @ttomsu, welcome!

Unlike the original `stanza` project, this repository is not meant to run as a standalone agent. Instead, it is embedded into the OpenTelemetry Collector. As a result, the focus of this repository is log collection and parsing, but exporting is handled by the OpenTelemetry Collector.

Let me know if you have any other questions.

**Comment by ttomsu** [comment]
Thanks for the quick reply!

Has the work to embed it in the Collector already been done? I did a quick search for "log-collection" in the Collector repo and I didn't find any mention of the package name `github.com/open-telemetry/opentelemetry-log-collection`. Is it similar to the way the Collector-contrib repo works (which I'm also not clear on -  are those run as separate binaries?)

**Comment by djaglowski** [comment]
Integration into the collector is partially done, but it's certainly not complete. 

You'll find a few receivers in the `collector-contrib` repo that are making use of this library. Specifically:
- [filelogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver)
- [syslogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/syslogreceiver)
- [tcplogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/tcplogreceiver)
- [udplogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/udplogreceiver)

You can follow overall progress of the effort on this [milestone](https://github.com/open-telemetry/opentelemetry-collector-contrib/milestone/8).
