### ISSUE TITLE
Add real filepath to the file input

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-log-collection#181]
[`include_file_path`](https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/docs/operators/file_input.md#configuration-fields) includes file path, but file path is not resolved in case of symbolic links:

file_path: STRING(/xyz/test_symbolic.log)
```
lrwxrwxrwx 1 drosiek drosiek 8 Jun 11 14:41 test_symbolic.log -> test.log
```

This seems to be important metadata for us and I would like to add `include_file_real_path`

**Comment by sumo-drosiek** [comment]
@djaglowski Any opinion on that proposal?

**Comment by djaglowski** [comment]
I definitely agree with the idea that this info needs to be obtainable.

We should also consider `include_file_name` in this decision.

This would give us:
`include_file_name`

**Comment by djaglowski** [comment]
I definitely agree with the idea that this info needs to be obtainable. 

We should also consider `include_file_name` in this decision.

Perhaps:
`include_file_name`
`include_file_path`
`include_file_name_resolved`
`include_file_path_resolved`
