### ISSUE TITLE
Resouce and Attributes should support arbitrary data

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-log-collection#190]
The otel-logs data model defines both [Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-resource) and [Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-attributes) as type `map<string, any>` (equivalent to `map[string]interface{}`. However, both are currently implemented as `map<string, string>` (equivalent to `map[string]string`).

Both fields should be updated from `map[string]string` to `map[string]interface{}`.

This change may have ramifications throughout this codebase. Some particular areas that will need addressing:
- Any operators that currently expect `map[string]string` must be updated to support `map[string]interface{}`.
- `Field` syntax should be updated to allow deeper references on `Resource` and `Attributes` (i.e. `$resource.one.two.value`)
- Any operator that currently manipulates Resource or Attributes fields (i.e. `move`, `copy`, etc) will require new unit tests to ensure that the new arbitrary data format is fully supported.

Other changes may be necessary, and if not addressed in the initial PR, should be captured and tracked via an issue.

**Comment by errordeveloper** [comment]
Having followed the slack thread, it looks `Entry` should look more like this:
```
type Entry struct {
        Timestamp    time.Time            `json:"timestamp"               yaml:"timestamp"`
        Body         interface{}          `json:"body"                    yaml:"body"`
        Attributes   []attribute.KeyValue `json:"attributes,omitempty"    yaml:"attributes,omitempty"`
        Resource     []attribute.KeyValue `json:"resource,omitempty"      yaml:"resource,omitempty"`
        SeverityText string               `json:"severity_text,omitempty" yaml:"severity_text,omitempty"`
        SpanId       []byte               `json:"span_id,omitempty"       yaml:"span_id,omitempty"`
        TraceId      []byte               `json:"trace_id,omitempty"      yaml:"trace_id,omitempty"`
        TraceFlags   []byte               `json:"trace_flags,omitempty"   yaml:"trace_flags,omitempty"`
        Severity     Severity             `json:"severity"                yaml:"severity"`
}
```

@djaglowski what do you think?

**Comment by djaglowski** [comment]
I think we should wait for resolution of [specification#1777](https://github.com/open-telemetry/opentelemetry-specification/pull/1777).

**Comment by errordeveloper** [comment]
@djaglowski thanks for xref, didn't know about that PR.

**Comment by errordeveloper** [comment]
Another question is this - would it be right to suggest switching to types gereated from [the protobuf](https://github.com/open-telemetry/opentelemetry-proto/blob/f3b0ee0861d304f8f3126686ba9b01c106069cb0/opentelemetry/proto/logs/v1/logs.proto)?

**Comment by errordeveloper** [comment]
Presently this is what generated `LogRecord` struct looks like:
```Go
// A log record according to OpenTelemetry Log Data Model:
// https://github.com/open-telemetry/oteps/blob/main/text/logs/0097-log-data-model.md
type LogRecord struct {
	// time_unix_nano is the time when the event occurred.
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	// Value of 0 indicates unknown or missing timestamp.
	TimeUnixNano uint64 `protobuf:"fixed64,1,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	// Numerical value of the severity, normalized to values described in Log Data Model.
	// [Optional].
	SeverityNumber SeverityNumber `protobuf:"varint,2,opt,name=severity_number,json=severityNumber,proto3,enum=opentelemetry.proto.logs.v1.SeverityNumber" json:"severity_number,omitempty"`
	// The severity text (also known as log level). The original string representation as
	// it is known at the source. [Optional].
	SeverityText string `protobuf:"bytes,3,opt,name=severity_text,json=severityText,proto3" json:"severity_text,omitempty"`
	// Short event identifier that does not contain varying parts. Name describes
	// what happened (e.g. "ProcessStarted"). Recommended to be no longer than 50
	// characters. Not guaranteed to be unique in any way. [Optional].
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// A value containing the body of the log record. Can be for example a human-readable
	// string message (including multi-line) describing the event in a free form or it can
	// be a structured data composed of arrays and maps of other values. [Optional].
	Body *v11.AnyValue `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	// Additional attributes that describe the specific event occurrence. [Optional].
	Attributes             []*v11.KeyValue `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty"`
	DroppedAttributesCount uint32          `protobuf:"varint,7,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"dropped_attributes_count,omitempty"`
	// Flags, a bit field. 8 least significant bits are the trace flags as
	// defined in W3C Trace Context specification. 24 most significant bits are reserved
	// and must be set to 0. Readers must not assume that 24 most significant bits
	// will be zero and must correctly mask the bits when reading 8-bit trace flag (use
	// flags & TRACE_FLAGS_MASK). [Optional].
	Flags uint32 `protobuf:"fixed32,8,opt,name=flags,proto3" json:"flags,omitempty"`
	// A unique identifier for a trace. All logs from the same trace share
	// the same `trace_id`. The ID is a 16-byte array. An ID with all zeroes
	// is considered invalid. Can be set for logs that are part of request processing
	// and have an assigned trace id. [Optional].
	TraceId []byte `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// A unique identifier for a span within a trace, assigned when the span
	// is created. The ID is an 8-byte array. An ID with all zeroes is considered
	// invalid. Can be set for logs that are part of a particular processing span.
	// If span_id is present trace_id SHOULD be also present. [Optional].
	SpanId               []byte   `protobuf:"bytes,10,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

Very notably, it's missing `Resource`, but has `Attributes` as a keyed list. And `Body` appears to be of type `AnyValue`, which only supports primitive types. Should the efforts be focused on ensuring protobuf is aligned with the spec as it currently stands?

**Comment by djaglowski** [comment]
You'll find that `LogRecord` inherits its `Resource` information a [higher level type](https://github.com/open-telemetry/opentelemetry-proto/blob/f3b0ee0861d304f8f3126686ba9b01c106069cb0/opentelemetry/proto/logs/v1/logs.proto#L28). That is, `LogRecords` are grouped together according to the `Resource` from which they were emitted.

**Comment by errordeveloper** [comment]
@djaglowski this gets rather confusing... so the data model specification has no bearing on the underlying data structures? This seems a bit unconventional to me, I've not seen this kind of approach in any other standards, and I thought I've read a few in the past.

**Comment by errordeveloper** [comment]
I opened https://github.com/open-telemetry/opentelemetry-proto/issues/318.

**Comment by chaitanyaphalak** [comment]
Hey @djaglowski for this one is the following necessary? Seems like it can be a separate PR/issue(I also don't understand why we need it)

- FIeld syntax should be updated to allow deeper references on Resource and Attributes (i.e. $resource.one.two.value)

**Comment by djaglowski** [comment]
Hi @chaitanyaphalak. I do think it is necessary. Users will need this in order to set or read nested attributes.

**Comment by djaglowski** [comment]
Having circled back on this issue and given it some additional thought, I think that the proposed changes should apply only to Attributes. 

Although the Logs Data Model specifies Resource as `map<string, any>`, all current semantic conventions for Resource attributes fit within a `map[string]string`. It's not clear that this library needs to support arbitrarily structured values in Resource.

**Comment by chaitanyaphalak** [comment]
Hey @djaglowski looks like the body field already supports the nested field syntax, should I change attributes and resources to the same implementation?

**Comment by djaglowski** [comment]
Thanks for the contribution @chaitanyaphalak. I'm taking a look at #401 now.

> body field already supports the nested field syntax, should I change attributes and resources to the same implementation?

I think the implementation will be similar, but there is an important distinction between body and attributes/resource, which is that the body is `interface{}` while the others will be `map[string]interface{}`. The practical difference here is that the body can itself be something other than a map (typically will just be a string). For this reason, attributes and resource will need a slightly different implementation. 

There is a related design decision that needs to be made as well. Basically, what is the exact expected behavior when a user attempts to interact directly with the base of "attributes" or "resource"? (e.g. `parse_to: attributes`) My intuition is that there will be a small number of sensible options for how this should work, and that it will depend to an extent on the context. For example, we already have some special (but I think intuitive) behavior in the [remove](https://github.com/open-telemetry/opentelemetry-log-collection/blob/4b4fcde6ce9db74e8168f2c834d268217cdc9832/operator/builtin/transformer/remove/rootable_field.go#L29) operator. The following will remove all key/value pairs from attributes.
```yaml
type: remove
field: attributes
```

I will take a closer look at this aspect of the design early next week, after cutting a release of this library. 

In the meantime, I think what you've done in #401 is non-breaking and could be done for resource as well. (Though I will hold it until after Monday's release) We can address the field syntax updates afterwards.

**Comment by chaitanyaphalak** [comment]
Thanks @djaglowski I will work on a similar PR for resource, and will wait for your thoughts on field syntax design.

Best of luck with the release!
