### ISSUE TITLE
Establish semantic convention for "file" attributes and ensure they are followed in this library

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-log-collection#191]
> I think we should look into standardizing file related attribute names as Otel semantic conventions.

_Originally posted by @tigrannajaryan in https://github.com/open-telemetry/opentelemetry-log-collection/pull/189#discussion_r652832722_

**Comment by tigrannajaryan** [comment]
@djaglowski does https://github.com/open-telemetry/opentelemetry-log-collection/pull/189 fully resolve this or there is more todo?

**Comment by chaitanyaphalak** [comment]
@djaglowski are the conventions for this one already merged?
