### ISSUE TITLE
Clarification for setting up InstrumentationLibrary log field as defined in logs proto when creating new receiver

### ISSUE THREAD

**Issue by AJ-54** [open-telemetry/opentelemetry-log-collection#217]
How can I set which `InstrumentationLibrary` I am using. As defined in the [logs proto](https://github.com/open-telemetry/opentelemetry-proto/blob/f3b0ee0861d304f8f3126686ba9b01c106069cb0/opentelemetry/proto/logs/v1/logs.proto#L47), I should be able to set this value if I am using the `
opentelemetry-log-collection` for creating log receivers. Can anyone help me out because I cannot see any paramter inside `entry.go` which is actually log level and setting up `InstrumentationLibrary` is on higher level.

**Comment by djaglowski** [comment]
This repo probably should not support this directly. However, I think it may be a reasonable feature request for receivers based on this repo. For that, I suggest opening an issue on the collector-contrib repo. I believe the suggestion would be that we add a parameter to `internal/stanza/config.go`'s `BaseConfig` struct, such that users may specify a value for `InstrumentationLibrary`. This value would then be attached during the conversion from this repo's `entry.go` to the collector's `pdata` representation.
