### ISSUE TITLE
journald input operator - add configurations for `unit` and `priority`

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-log-collection#251]
User would like to select which services to collect (`-u` args, it can be any number of services) and select priority ( `-p` args) 

https://www.commandlinux.com/man-page/man1/journalctl.1.html

**Comment by rockb1017** [comment]
Thanks, @djaglowski when is the next release scheduled?

**Comment by djaglowski** [comment]
@rockb1017 We haven't established a release schedule, so releases are currently as needed. I'm happy to create a release tomorrow. Ideally, #232 will be resolved prior to the next release, so we can be confident that we're not breaking contrib.
