### ISSUE TITLE
Codecov ignores Windows build tags

### ISSUE THREAD

**Issue by jsirianni** [open-telemetry/opentelemetry-log-collection#285]
While reviewing CI for this pull request https://github.com/open-telemetry/opentelemetry-log-collection/pull/283, we noticed that Codecov did not consider source files with windows build tags.

Initially, Codecov failed due to xml.go's lack of coverage, however, once adding the windows build tag to xml.go, Codecov no longer caught this problem.

If supported by Code Coverage, Windows specific builds should be tested.

**Comment by djaglowski** [comment]
This is tangential to the issue, but the `xml.go` file was originally written in such a way that it could be validated on any OS. Although it is used for WEL parsing, it is really just a string parsing operation.
