### ISSUE TITLE
feature request: journald input - run `journalctl` seperately for each service unit

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-log-collection#286]
we can now provide list of units to collect in array, but we cannot configure other options for each unit. 
for example, i want to collect "error" log level for `kubelet.service` but i want "info" for `ssh.service`

**Comment by djaglowski** [comment]
Typically, I would expect to use multiple instances of the operator in such a case. Is there a reason why this is not a reasonable approach?

**Comment by rockb1017** [comment]
oh hmm you are right, that is possible. Thanks!
