### ISSUE TITLE
feature request: flush timeout for `recombine` operator

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-log-collection#306]
there is no flush timeout implemented for `recombine` operator. 
I would like it to flush whatever it has when it doesn't receive any new logs for 5 or 10 seconds.

**Comment by pmalek-sumo** [comment]
Here's my attempt at this: #325

**Comment by dmitryax** [comment]
@rockb1017 @pmalek-sumo is this ticket resolved?

**Comment by pmalek-sumo** [comment]
I do believe so since #325 is merged.

**Comment by djaglowski** [comment]
Resolved by #325
