### ISSUE TITLE
Keep on trying to open an invalid symbol link file

### ISSUE THREAD

**Issue by polarG** [open-telemetry/opentelemetry-log-collection#342]
I think this is an enhancement, not bug.

Description:
In my K8s cluster, there are some symbol links under /var/log/containers. This means the linked files under /va/lib/docker/containers are not exists. But i do not know when the linked files were removed, or why containers are deleted but the links still there.
The otel collector keep on trying to open these linked files every seconds. 

Proposed enhancement.
Although this may not introduce faults, it still waste the system resource. If there is some mechanism to verify the file is valid or limitation on trying, that will be better.

@tigrannajaryan 
@rockb1017

**Comment by tigrannajaryan** [comment]
What's the current behavior? Do we print errors in the log when we cannot follow a symlink? Are there measurable performance implication or they negligible?

**Comment by polarG** [comment]
From the log, we are following an invalid symlink. and keep on printing the error msg.
Error msg: 
2022-01-24T19:31:54.592Z	error	Failed to open file	{"kind": "receiver", "name": "filelog", "operator_id": "$.file_input", "operator_type": "file_input", "error": "open /var/log/pods/kube-system_antrea-agent-mc7pl_51d08697-1a71-4062-b749-15c4a2cd69fe/install-cni/0.log: no such file or directory"}

There is no performance implication, but this message was printed too frequently, and it is difficult to follow other logs.

**Comment by djaglowski** [comment]
I think probably we should just change [this log](https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/operator/builtin/input/file/file.go#L209:L213) level to debug. There are other ways in which a file can fail to open but I think typically this would be about the same level of concern.

**Comment by polarG** [comment]
Yeap, this is a good solution. Thanks.
