### ISSUE TITLE
Multiline breaker not work correctly in k8s

### ISSUE THREAD

**Issue by polarG** [open-telemetry/opentelemetry-log-collection#343]
**Description**:
The multiline breaker was not work at the beginning of parse. The events received were single line but not as multiline configured.  After sometimes, it worked as expected.

**Configuration**:
logsCollection:
  containers:
    multilineConfigs:
      - namespaceName:
          value: default
        podName:
          value: gogen*
          useRegexp: true
        containerName:
          value: cputime-perfmon
        firstEntryRegex: ^\d{2}\/\d{2}\/\d{4} \d{2}:\d{2}:\d{2}.\d{6}
      - namespaceName:
          value: default
        podName:
          value: gogen*
          useRegexp: true
        containerName:
          value: change-security-1102-windows
        firstEntryRegex: ^\d{2}\/\d{2}\/\d{4} \d{2}:\d{2}:\d{2} [AaPp][Mm]

**Log sample**

12/29/2021 00:00:36.993565
collection="CPU Load"
object=Processor
counter="% Idle Time"
instance="1"
Value=10

12/29/2021 12:00:37 AM  
LogName=Security  
SourceName=Microsoft-Windows-Eventlog  
EventCode=1102  
EventType=4  
Type=Information  
ComputerName=BobbyGenovese-mbp13  
TaskCategory=Log clear  
OpCode=Info  RecordNumber=2450  
Keywords=Audit Success  
Message=The audit log was cleared.  
Subject: 
              Security ID:    S-1-5-21-1850455071-2977647103-2170296691-1000
              Account Name:   HaePugliese
              Domain Name:    SPLUNK5
              Logon ID:       0x77220

@tigrannajaryan 
@rockb1017

**Comment by djaglowski** [comment]
Hi @polarG, this config format does not appear to be for this library. Are you sure this is correct repository?

**Comment by rockb1017** [comment]
this is with fluentd agent. if you believe this is a bug, create an issue here. 
https://github.com/signalfx/splunk-otel-collector-chart
and can you post the values.yaml snippet wrapped in ``` ?

**Comment by djaglowski** [comment]
Closing this issue based on @rockb1017's comment.
