### ISSUE TITLE
data duplication at the beginning of log file

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-log-collection#391]
during perf test, I often see that the begging of log is consumed twice. (first 300~500 events out of 200,000) 
I will be looking into it. If anyone has an idea on how to fix it, please share.

**Comment by djaglowski** [comment]
This sounds likely to be related to the fingerprint of a file. Basic idea would be that the file is forgotten and ingested from the start again.

Can you confirm it is only appending to files? Any other information you can share about how the test scenario interacts with or manages the files?

**Comment by rockb1017** [comment]
> Can you confirm it is only appending to files?
@djaglowski Could you clarify what you meant ? 

I run otel collector in k8s environment. it is tailing all container files. I deploy 5 loggen pods. log rotation doesn't happen. so that is out of the picture. 
![image](https://user-images.githubusercontent.com/12387289/155283746-3ce4ffe2-7d65-47ec-8317-b6855dc3c908.png)

5 out of 2 pods have some data duplication. (beginning of files) 

here is example of my loggen pod logs.
```
{"log":"---begin---\n","stream":"stdout","time":"2022-02-23T08:07:01.411341038Z"}
{"log":"num: 1 | loggen-spt76 | 2022-02-23T08:07:01.411116 | rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr\n","stream":"stdout","time":"2022-02-23T08:07:01.411378225Z"}
{"log":"num: 2 | loggen-spt76 | 2022-02-23T08:07:01.411447 | rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr\n","stream":"stdout","time":"2022-02-23T08:07:01.411564593Z"}
```
Note that pod name is included in the log line. so all loggen pod logs are unique.

**Comment by rockb1017** [comment]
1 out of 8 
![image](https://user-images.githubusercontent.com/12387289/155284574-73ea1b4a-33c0-4849-b4e7-1b9346d22791.png)

**Comment by rockb1017** [comment]
I think it could be coming from here.
https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/operator/input/file/file.go#L200-L223
we are removing items from array while we loop through it. i think I can add `i--` whenever we remove fps and file. 
Let me change and run tests.
