### ISSUE TITLE
time_parser operator not parsing timestamps from 1970 as expected

### ISSUE THREAD

**Issue by dnitschke-splunk** [open-telemetry/opentelemetry-log-collection#414]
### Issue
When parsing a timestamp from the year 1970, the resulting `$timestamp` actually time travels to the current or previous year. E.g, parsing `0` seconds since the Unix epoch or the corresponding `Thu 1 Jan 1970 00:00:00 UTC` on `Feb 24, 2022` will result in `1640995200000000000` or `Sat 1 Jan 2022 00:00:00 UTC`. This is true for all three settings of layout type tested, namely `epoch`, `gotime`, and `strptime`. Expectation was that `$timestamp` matches `0` nanoseconds since the Unix epoch. 

### Analysis
Checking [https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/operator/helper/time.go#L285](https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/operator/helper/time.go#L285) tells us that we want to be able to handle timestamps without a given year. Therefore, we check whether the `Year()` of the already parsed timestamp is greater than `1970`. If not, we make a decision whether the current year or the previous one should be used. This means that all timestamps before the year `1971` automatically time travel to the current or previous year.

### Suggestion
However, it is my understanding, that `time.ParseInLocation()` will set `Year()` to `0` for timestamps that do not contain a year explicitly, see [https://pkg.go.dev/time#Parse](https://pkg.go.dev/time#Parse). Therefore, IMHO we could just check whether `Year()` is `0` to identify timestamps without a year and leave all other timestamps that represent a valid timestamp in uint64 nanoseconds since the epoch untouched. This would allow to set `$timestamp` to values from `1970` and to `0` in particular (an exporter might handle this timestamp in a special manner, see, e.g., [splunkhecexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a72a6496db34773e39c344f96b1cd8f28c5dc3d7/exporter/splunkhecexporter/logdata_to_splunk.go#L142)).

**Comment by djaglowski** [comment]
@dnitschke-splunk, thank you for the details write up. #417 implements your suggestion.
