### ISSUE TITLE
Small typo in `recombine` readme

### ISSUE THREAD

**Issue by matthewmodestino** [open-telemetry/opentelemetry-log-collection#451]
Noticed simple typo in recombine readme while testing new `source_identifier` parameter. 

"attributes" spelled wrong in the default settings table:

https://github.com/open-telemetry/opentelemetry-log-collection/blob/6bc7c94635ce03bf6182d56aec7ef43bba798cf7/docs/operators/recombine.md?plain=1#L19

**Comment by djaglowski** [comment]
Thanks @matthewmodestino!
