### ISSUE TITLE
Migrate Key-Value parser from stanza

### ISSUE THREAD

**Issue by crobertson-conga** [open-telemetry/opentelemetry-log-collection#455]
Stanza recently included a key-value parser for logs:

https://github.com/observIQ/stanza/blob/main/docs/operators/key_value_parser.md

Several applications, like loki, leverage this instead of something like json for structured logs.

**Comment by djaglowski** [comment]
Hi @crobertson-conga. PR #307 would accomplish this. It's been stalled for a while but hopefully we'll see this completed soon. In the mean time, we did not have a tracking issue for that PR, so this issue can serve that purpose.

**Comment by jsirianni** [comment]
@djaglowski I will follow up on the PR feedback 👍
