### ISSUE TITLE
Archive the repo

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-log-collection#491]
Should this repo be archived given that OTel collector contrib doesn't depend on it anymore https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10187?

cc @djaglowski

**Comment by djaglowski** [comment]
Yes, but there are a few things we should do first:
- Final prune of issues & PRs
- Close PRs w/ direction to reopen
- Rename and migrate issues
- Update readme

I am planning to do all of this, but have not had a chance yet.

**Comment by djaglowski** [comment]
@tigrannajaryan or @bogdandrutu, this repo is ready to be archived. I do not have permissions to do this. Would one of you please do the honors?

**Comment by dmitryax** [comment]
> - Final prune of issues & PRs
> - Close PRs w/ direction to reopen
> - Rename and migrate issues

I believe these 3 items can be done after archiving, otherwise we can accumulate more of new ones :)
