### ISSUE TITLE
Rename "record" to "body"

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-log-collection#83]
The logs specification uses the term "body", so this would align terminology.

**Comment by lastchiliarch** [comment]
Seems like we should rename Entry.Record to Entry.Body and all the relevant files ,  https://github.com/open-telemetry/opentelemetry-log-collection/blob/0356f77b26ca5fa4800be24ed21e2f7ea40cbfaf/entry/entry.go#L50.

Any details? I'd like to take this.

**Comment by djaglowski** [comment]
@lastchiliarch Thank you!

You've got the right idea. Let me know if you run into any complexities. Otherwise, I believe it's just a very detail oriented task.

**Comment by djaglowski** [comment]
Closed via #88
