### ISSUE TITLE
Add fieldalignment make target

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-log-collection#98]
See #95

It would be nice to have this functionality readily available so we can easily identify further improvements, and also so that we can easily validate that we have not regressed.

**Comment by chasekiefer** [comment]
Do you want a specific target to run this? Otherwise I can just add the [maligned](https://github.com/mdempsky/maligned) linter to the .golangci.yml configuration. Maligned seems to be the golangci-lint supported version of fieldalignment.

**Comment by djaglowski** [comment]
`maligned` appears to be deprecated, and suggests to use `fieldalignment` instead, so I think we should follow that.

I think a new make target is fine for this. The goal here is not really to aggressively push for these optimizations, but rather to ensure that when a developer chooses to optimize, they are doing so in a consistent manner.

**Comment by pmalek-sumo** [comment]
@djaglowski Please take a look at my proposal in https://github.com/open-telemetry/opentelemetry-log-collection/pull/218

There's more to be changed in code but I've demonstrated a gradual approach by changing just a handful of files.

**Comment by djaglowski** [comment]
Closing due to #218
